version: "3"
services:
  php:
    container_name: php8
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    networks:
      - internal
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./arquivos/:/var/www/
  nginx:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./arquivos/:/var/www
networks:
  internal:
    driver: bridge
